version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linebot-app-1201"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14iqkqxdotyj9"
s3_prefix = "linebot-app-1201"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LineChannelAccessToken=\"79FhFwqMfC3rasF+/B/Ca6KV6G9vO0NjtaFMyHacjM/S6Rv8woy3Gp8r0OvAqXgMnB/Ur1i60QXu9tzwi14WEWvsvGttQndNGixbDFhBhEUA7Dy1iVQfhv1Q2U1tBZD6GFQxpUDwvhoxFWo8Ge0JNQdB04t89/1O/w1cDnyilFU=\" LineChannelSecret=\"ef1e58b0cb4e7e0777f0d680563d2000\""
image_repositories = []
